In [1]:
import pandas as pd
import sklearn
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from gensim.models import KeyedVectors

model = KeyedVectors.load_word2vec_format('/Users/carlos/Downloads/wiki.en.vec')

In [3]:
print(model.most_similar('teacher'))

/usr/local/lib/python2.7/site-packages/gensim/matutils.py:737: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if np.issubdtype(vec.dtype, np.int):


[(u'teache', 0.7893733382225037), (u'teacher,', 0.7844662070274353), (u'teachers', 0.7713974714279175), (u'teacherman', 0.7344009280204773), (u'teached', 0.7318561673164368), (u'teacher/pupil', 0.729202926158905), (u'teachers`', 0.7286232113838196), (u'schoolteacher', 0.7279092073440552), (u'teachera', 0.7274622917175293), (u'\u2018teacher', 0.7261091470718384)]


In [4]:
print(model.most_similar('soccer'))

[(u'soccer/lacrosse', 0.7822386026382446), (u'occer', 0.7781806588172913), (u'soccer/softball', 0.7671366930007935), (u'lacrosse/soccer', 0.7663369178771973), (u'soccers', 0.7609419226646423), (u'soccer\u2014', 0.7531135082244873), (u'football/soccer/lacrosse', 0.7432413101196289), (u'soccer,and', 0.7427438497543335), (u'msoccer', 0.7422813773155212), (u'soccer,', 0.7378698587417603)]


In [5]:
print(model.most_similar('moon'))

[(u'lunar', 0.7346395254135132), (u'moons', 0.7316275835037231), (u'lunarr', 0.6258058547973633), (u'phobos', 0.6219738721847534), (u'sun/moon', 0.6167811155319214), (u'moonlee', 0.6117098927497864), (u'uranus', 0.6112249493598938), (u'moonbyul', 0.6105742454528809), (u'moon,', 0.6081600189208984), (u'\u2014lunar', 0.607763409614563)]


In [6]:
print(model.similarity('soccer', 'baseball'))

0.6651899


In [7]:
print(model.similarity('soccer', 'car'))

0.21370612


In [8]:
words = []
for word in model.vocab:
    words.append(word)

# Printing out number of tokens available
print("Number of Tokens: {}".format(len(words)))

Number of Tokens: 2519370


In [9]:
# Printing out the dimension of a word vector 
print("Dimension of a word vector: {}".format(
    len(model[words[0]])
))

Dimension of a word vector: 300


In [10]:
# Print out the vector of a word 
print("Vector components of a word: {}".format(
    model[words[0]]
))

Vector components of a word: [-0.060585  -0.35465    0.091571   0.37924   -0.43332    0.33352
 -0.039997  -0.36795   -0.054958  -0.054794  -0.23318    0.26513
 -0.64387    0.25681   -0.24388   -0.17607   -0.034843   0.026851
  0.06506    0.1481    -0.41027    0.13094   -0.34636    0.33094
 -0.31887   -0.0065675 -0.17026    0.015678   0.12418    0.086442
  0.1091    -0.16714   -0.41878    0.24766   -0.049762  -0.35074
  0.081695  -0.53918   -0.21191   -0.68771    0.27134    0.20855
 -0.0080212  0.23765    0.24037   -0.27663   -0.056412  -0.26021
 -0.27986   -0.2049    -0.47042    0.19775   -0.14586    0.41511
 -0.45645   -0.028102  -0.34122    0.073674   0.12847    0.62578
 -0.066765   0.24551    0.62374   -0.068045   0.10239   -0.16786
 -0.50368    0.033411  -0.089627  -0.25144    0.12825    0.049497
 -0.50959    0.17839   -0.12124    0.7831     0.11123    0.48259
  0.048027  -0.25611   -0.0076265  0.24399   -0.16697    0.21499
 -0.255      0.12175    0.28555    0.8288     0.0078243 -0

In [12]:
find_similar_to = 'car'

# Finding out similar words [default= top 10]
for similar_word in model.similar_by_word(find_similar_to):
    print("Word: {0}, Similarity: {1:.2f}".format(
        similar_word[0], similar_word[1]
    ))

Word: cars, Similarity: 0.83
Word: automobile, Similarity: 0.72
Word: truck, Similarity: 0.71
Word: motorcar, Similarity: 0.70
Word: vehicle, Similarity: 0.70
Word: driver, Similarity: 0.69
Word: drivecar, Similarity: 0.69
Word: minivan, Similarity: 0.67
Word: roadster, Similarity: 0.67
Word: racecars, Similarity: 0.67


In [18]:
word_add = ['lisboa', 'spain']
word_sub = ['portugal']

# Word vector addition and subtraction 
for resultant_word in model.most_similar(
    positive=word_add, negative=word_sub
)[0:2]:
    print("Word : {0} , Similarity: {1:.2f}".format(
        resultant_word[0], resultant_word[1]
    ))

Word : madrid , Similarity: 0.70
Word : valencias , Similarity: 0.70


In [19]:
word_add = ['king', 'woman']
word_sub = ['man']

# Word vector addition and subtraction 
for resultant_word in model.most_similar(
    positive=word_add, negative=word_sub
)[0:2]:
    print("Word : {0} , Similarity: {1:.2f}".format(
        resultant_word[0], resultant_word[1]
    ))

Word : queen , Similarity: 0.66
Word : princess , Similarity: 0.58


In [20]:
word_add = ['soccer', 'basket']
word_sub = ['foot']

# Word vector addition and subtraction 
for resultant_word in model.most_similar(
    positive=word_add, negative=word_sub
)[0:2]:
    print("Word : {0} , Similarity: {1:.2f}".format(
        resultant_word[0], resultant_word[1]
    )) 

Word : basketball , Similarity: 0.61
Word : basketball,volleyball , Similarity: 0.57


In [17]:
word_add = ['corinthians', 'argentina']
word_sub = ['brazil']

# Word vector addition and subtraction 
for resultant_word in model.most_similar(
    positive=word_add, negative=word_sub
)[0:2]:
    print("Word : {0} , Similarity: {1:.2f}".format(
        resultant_word[0], resultant_word[1]
    )) 

Word : _corinthians , Similarity: 0.61
Word : argentinos , Similarity: 0.59


In [18]:
df_train = pd.read_table("r8-train-no-stop.txt", header=None)
df_test = pd.read_table("r8-test-no-stop.txt", header=None)

In [19]:
df_train.head()

0                                                  1
0  earn  champion products approves stock split champio...
1   acq  computer terminal systems cpml completes sale ...
2  earn  cobanco inc cbco year net shr cts dlrs net ass...
3  earn  international inc qtr jan oper shr loss two ct...
4  earn  brown forman inc bfd qtr net shr dlr cts net m...

In [20]:
df_train.columns = ['tag','text']
df_test.columns = ['tag','text']

In [21]:
df_train.tag.value_counts()

earn        2840
acq         1596
crude        253
trade        251
money-fx     206
interest     190
ship         108
grain         41
Name: tag, dtype: int64

In [22]:
class MeanEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        # if a text is empty we should return a vector of zeros
        # with the same dimensionality as all the other vectors
        self.dim = 300

    def fit(self, X, y):
        return self

    def transform(self, X):
        return np.array([
            np.mean([self.word2vec[w] for w in words if w in self.word2vec]
                    or [np.zeros(self.dim)], axis=0)
            for words in X
        ])

In [23]:
vector = MeanEmbeddingVectorizer(model)

In [24]:
X_train = vector.transform(df_train['text'])
X_test = vector.transform(df_test['text'])

In [25]:
X_train.shape

(5485, 300)

In [26]:
X_test.shape

(2189, 300)

In [27]:
from sklearn.preprocessing import LabelEncoder

In [28]:
le = LabelEncoder()

In [29]:
y_train = le.fit_transform(df_train.tag)
y_test = le.transform(df_test.tag)

In [30]:
y_train

array([2, 0, 2, ..., 2, 5, 6])

In [31]:
df_train.tag.head()

0    earn
1     acq
2    earn
3    earn
4    earn
Name: tag, dtype: object

In [32]:
unique, counts = np.unique(y_train, return_counts=True)
print np.asarray((unique, counts)).T

[[   0 1596]
 [   1  253]
 [   2 2840]
 [   3   41]
 [   4  190]
 [   5  206]
 [   6  108]
 [   7  251]]


In [40]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=500, random_state=42, max_depth=5, max_features=50)

In [41]:
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features=50, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [42]:
rf.predict(X_test)

array([0, 0, 0, ..., 0, 0, 0])

In [43]:
y_test

array([7, 3, 6, ..., 1, 0, 6])

In [44]:
rf.predict_proba(X_test)

array([[0.47042564, 0.0745147 , 0.16896657, ..., 0.05537622, 0.04395853,
        0.11829636],
       [0.50214184, 0.06230765, 0.15607123, ..., 0.06882188, 0.03916819,
        0.09554233],
       [0.50029993, 0.06113978, 0.18095292, ..., 0.04716504, 0.0490441 ,
        0.09404471],
       ...,
       [0.49630306, 0.08287628, 0.16770939, ..., 0.04952111, 0.04212372,
        0.10405391],
       [0.64714245, 0.03553916, 0.162905  , ..., 0.03385341, 0.03228149,
        0.04100206],
       [0.62490188, 0.03908512, 0.15539071, ..., 0.03728763, 0.03422943,
        0.05339167]])

In [45]:
from sklearn.metrics import classification_report

In [46]:
print(classification_report(y_test, rf.predict(X_test)))

             precision    recall  f1-score   support

          0       0.59      0.82      0.68       696
          1       0.00      0.00      0.00       121
          2       0.83      0.93      0.88      1083
          3       0.00      0.00      0.00        10
          4       1.00      0.04      0.07        81
          5       1.00      0.03      0.07        87
          6       0.00      0.00      0.00        36
          7       0.00      0.00      0.00        75

avg / total       0.67      0.72      0.66      2189

